SCHEMA_TYPE = '__schema_type__'
VARIADIC_TYPE = '__variadic_type__'
DEBUG = 'debug_'
DATETIMETZ_FORMAT = "%Y-%m-%dT%H:%M:%S%z"

DEFAULT_CHUNK_SIZE = 1024  # tokens
DEFAULT_CHUNK_OVERLAP = 20  # tokens
DEFAULT_SIMILARITY_TOP_K = 2
DEFAULT_IMAGE_SIMILARITY_TOP_K = 2

DEFAULT_TEXT_KEY = "text"
DEFAULT_EMBEDDING_KEY = "embedding"
DEFAULT_DOC_ID_KEY = "doc_id"

GRAPH_TRIPLET_SOURCE_KEY = "triplet_source_id"
GRAPH_VECTOR_SOURCE_KEY = "vector_source_id"
GRAPH_NODES_KEY = "graph_nodes"
GRAPH_RELATIONS_KEY = "graph_relations"
GRAPH_SOURCE_REL = "SOURCE"